# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[(b'USER_LOCATION', b'USER_LOCATION'), (b'DESTINATION', b'DESTINATION'), (b'DEST_CHOICES', b'DEST_CHOICES'), (b'ARRIVED', b'ARRIVED')], default=(b'USER_LOCATION', b'USER_LOCATION'), max_length=13)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('start_location', models.CharField(blank=True, max_length=30, null=True)),
                ('end_location', models.CharField(blank=True, max_length=30, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
