# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='userhealthinformation',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), null=True, size=20),
        ),
    ]
