# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190623_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('address', models.CharField(max_length=100)),
                ('estimated_time', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='directionthread',
            name='current_step',
            field=models.CharField(choices=[(b'USER_LOCATION', b'USER_LOCATION'), (b'DESTINATION', b'DESTINATION'), (b'DEST_CHOICES', b'DEST_CHOICES'), (b'ARRIVED', b'ARRIVED')], default=b'USER_LOCATION', max_length=13),
        ),
        migrations.AddField(
            model_name='place',
            name='direction_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_list', to='backend.DirectionThread'),
        ),
    ]
