# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190623_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='estimated_time',
        ),
        migrations.AlterField(
            model_name='directionthread',
            name='current_step',
            field=models.CharField(choices=[(b'USER_LOCATION', b'USER_LOCATION'), (b'DESTINATION', b'DESTINATION'), (b'DEST_CHOICES', b'DEST_CHOICES'), (b'IN_TRANSIT', b'IN_TRANSIT'), (b'ARRIVED', b'ARRIVED')], default=b'USER_LOCATION', max_length=13),
        ),
        migrations.AlterField(
            model_name='place',
            name='distance',
            field=models.CharField(max_length=10),
        ),
    ]
