# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190623_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionthread',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
