# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190623_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionthread',
            name='current_step',
            field=models.CharField(default=b'USER_LOCATION', max_length=13),
        ),
        migrations.AlterField(
            model_name='directionthread',
            name='end_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directionthread',
            name='start_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
